apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nfs-provisioner.fullname" . }}-config
  labels:
    name: {{ template "nfs-provisioner.fullname" . }}-config 
data:
  config: |-
    ###################################################
    #
    # Ganesha Config Example
    #
    # This is a commented example configuration file for Ganesha.  It is not
    # complete, but only has some common configuration options.  See the man pages
    # for complete documentation.
    #
    ###################################################
    
    ## These are core parameters that affect Ganesha as a whole.
    NFS_CORE_PARAM {
      ## Allow NFSv3 to mount paths with the Pseudo path, the same as NFSv4,
      ## instead of using the physical paths.
      mount_path_pseudo = true;
    
      ## Configure the protocols that Ganesha will listen for.  This is a hard
      ## limit, as this list determines which sockets are opened.  This list
      ## can be restricted per export, but cannot be expanded.
      Protocols = 3,4;
    }
    
    ## These are defaults for exports.  They can be overridden per-export.
    EXPORT_DEFAULTS {
      ## Access type for clients.  Default is None, so some access must be
      ## given either here or in the export itself.
      Access_Type = RW;
      Protocols = 3,4;
      #SecType = "sys";
      Squash = root_squash;
    }
    
    ## Configure settings for the object handle cache
    MDCACHE {
      ## The point at which object cache entries will start being reused.
      #Entries_HWMark = 120000;
    }
    
    ## Configure an export for some file tree
    EXPORT
    {
      ## Export Id (mandatory, each EXPORT must have a unique Export_Id)
      Export_Id = 12345;
    
      ## Exported path (mandatory)
      Path = /export;
    
      ## Pseudo Path (required for NFSv4 or if mount_path_pseudo = true)
      Pseudo = /;
    
      ## Restrict the protocols that may use this export.  This cannot allow
      ## access that is denied in NFS_CORE_PARAM.
    
      #Access = "*"
      ## Access type for clients.  Default is None, so some access must be
      ## given. It can be here, in the EXPORT_DEFAULTS, or in a CLIENT block
      #Access_Type = RW;
    
      ## Whether to squash various users.
          #Squash = root_squash;
    
      ## Allowed security types for this export
      #Sectype = sys,krb5,krb5i,krb5p;
    
      ## Exporting FSAL
      FSAL {
        Name = VFS;
      }
    
      ###CLIENT
      ###{
      ### Clients = "10.0.0.1/8";
      ###}
    }
    
    ## Configure logging.  Default is to log to Syslog.  Basic logging can also be
    ## configured from the command line
    LOG {
      ## Default log level for all components
      COMPONENTS {
        ALL = Full_Debug;
      }
    }
    
    NFS_Core_Param
    {
        MNT_Port = 20048;
        NLM_Port = 32803;
        fsid_device = true;
    }
    
    NFSV4
    {
        Grace_Period = 120;
    }
  rsync_config: |-
    pid file = /var/run/rsyncd.pid
    lock file = /var/run/rsync.lock
    log file = /var/log/rsync.log
    dont compress   = *.gz *.tgz *.zip *.z *.Z *.rpm *.deb *.bz2
    
    [files]
    path = /export
    comment = RSYNC FILES
    read only = false
    timeout = 300
